BGDIINF_SB-1799: Implement post endpoint
geoadmin/service-kml pull request #4
Opened 2021-06-09 09:37 UTC by IsabelleBzr

Currently completed work on the post endpoint. I am now making a PR that I can make the AWS ECR into a separate branch and the PR will not be too big. The unittest will be extended at a later time in ticket [BGDIINF_SB-1816](https://jira.swisstopo.ch/browse/BGDIINF_SB-1816).

2021-06-09 10:49 UTC, ltshb requested changes

2021-06-09 10:49 UTC, ltshb commented on app/__init__.py
> +#         abort(make_error_msg(403, 'Not allowed'))
Either remove this or add a `TODO CLEAN_UP`  comment to not forget about it.

2021-06-09 10:49 UTC, ltshb commented on app/helpers/response_generation.py
> +        }
CORS headers should be managed globally. See app/__init__.py:24

2021-06-09 10:49 UTC, ltshb commented on app/helpers/utils.py
> +from defusedxml.ElementTree import ParseError
Imports are not sorted, use `isort`

2021-06-09 10:49 UTC, ltshb commented on app/helpers/utils.py
> +    kml_string = re.sub(r'on\w*=(".+?"|\'.+?\')', '', kml_string, flags=re.IGNORECASE)
A small docstring that explain what this function does, e.g. remove all attributes with `on` prefix and remove all `script` elements.

2021-06-09 10:49 UTC, ltshb commented on app/helpers/utils.py
> +        abort(415, 'Only valid KML file are accepted')
Here it should return a 400 Bad Request and not 415 Media Type Unsupported. Message should be 'Invalid KML file'

2021-06-09 10:49 UTC, ltshb commented on app/helpers/utils.py
> +        abort(413, error_msg)
Don't use old style  `%` string formatting (except for debug, info and warning logs). Also add the actual size to the log message. Might be good to print the size in MB for better readability.

2021-06-09 10:49 UTC, ltshb commented on app/helpers/utils.py
> +    return inner_decorator
Be more precise in the name of the method, it only validate the content type header not the content, so `validate_content_type` is better

2021-06-10 08:23 UTC, hansmannj commented on app/helpers/utils.py
> +    return inner_decorator
Nice! :slightly_smiling_face:

2021-06-10 08:26 UTC, hansmannj approved these changes
:1st_place_medal: 
Already some useful unit tests :+1:

2021-06-10 09:00 UTC, ltshb approved these changes
Just minor improvements

2021-06-10 09:00 UTC, ltshb commented on app/helpers/utils.py
> +    return bytes / (b_size**a[to])
Nice methods however I would change it as follow:

```python
def bytes_to(bytes, to, b_size=1024):
    a = {'kb': 1, 'mb': 2, 'gb': 3, 'tb': 4}
    r = float(bytes)
    return bytes / (b_size**a[to.lower()])
```
This made the usage clearer ;-) also peta und exa bytes are not needed.

2021-06-10 09:00 UTC, ltshb commented on app/helpers/utils.py
> +        abort(413, error_msg)
You don't need to generate the mb version, just do it on the fly in the error message formatting

`f"File size exceed {bytes_to(max_file_size, 'MB')} MB. The actual file size is {bytes_to(len(kml_string), 'MB')} MB"`
or 
`'File size exceed {} MB. The actual file size is {} MB'.format(
            bytes_to(max_file_size, 'MB'), bytes_to(len(kml_string), 'MB')
        )`

2021-06-14 06:38 UTC, merged